### ISSUE TITLE
the problem when when using transform: scale()

### ISSUE THREAD

**Issue by mfma** [bokuweb/react-rnd#110] opened 2017-05-03 16:02 UTC
When the parent box add  "transform:scale()", rnd is incorrect to drag or resize it。

**Comment by bokuweb** [comment] 2017-09-15 22:56
@mfma Could you please provide reproduced project on webpackbin with latest version rnd? https://www.webpackbin.com/bins/-Ku4nRhImIfnt9N08lGu

**Comment by ryanlegler** [comment] 2017-10-16 17:55
See example below where I've added a "transform:scale()" to parent div.
https://www.webpackbin.com/bins/-KwaJCSIKJcVRtsZ5Hn4

**Comment by bokuweb** [comment] 2017-10-17 01:39
@ryanlegler Thanks. If you set `transform:scale` to Rnd component directly, `transform` is overwritten by `react-draggable` probably.

See related issue, https://github.com/bokuweb/react-rnd/issues/185

**Comment by ryanlegler** [comment] 2017-10-20 03:09
@bokuweb thanks for your response - I think the issue described here is slightly different than the related issue you linked to. The scale in question is on a parent div of the react-draggable component. The issue isn't that the scale is overwritten, it's that the pixel calculation made by react-rnd are incorrect because of the scaled context that it's in.  From digging around a bit i found this:  https://github.com/mzabriskie/react-draggable/pull/217/files Looks like this issue is being looked at. Hopefully the pull request will get merged in so the scale param could be exposed in react-rnd.

**Comment by maixing** [comment] 2017-12-28 07:56
Please merge

**Comment by koutsenko** [comment] 2018-01-17 12:51
Any news?

**Comment by gaddafirusli** [comment] 2018-06-07 08:39
Would love to get this one merged too. Any updates?

**Comment by travisdahl** [comment] 2018-11-15 00:06
I was hoping as an escape hatch that this would work, but alas, it does not...

```
    const style = {
      transform: `translate(${x}px, ${y}px) scale(0.8) !important`
    };

      <Rnd
        style={style}
...
```

**Comment by kv9991** [comment] 2018-11-23 12:46
+1. Still can't solve this problem
But this looks like good escape https://github.com/mzabriskie/react-draggable/pull/217/files

**Comment by cadrell0** [comment] 2018-12-21 13:36
The scale prop has been implemented in react-draggable and re-resizable

https://github.com/bokuweb/re-resizable/pull/388
https://github.com/mzabriskie/react-draggable/pull/352

**Comment by mecawish** [comment] 2019-01-28 14:33
Hi! Can we update the `react-draggable` dependency to the current version? It seems that the `scale` issue is already addressed there.

**Closed** 2019-01-30 09:02 UTC
Labels: PR_Welcome, depends on other repo, need more info

**Comment by mecawish** [comment] 2019-01-31 08:37
Working now. Thank you so much, @bokuweb !

**Comment by Hello-Tan** [comment] 2019-02-13 09:12
> @mfma @ryanlegler @koutsenko @ g33kidd @gaddafirusli @travisdahl @ kv9991 @ cadrell0 @ AhmedSayed77 @mecawish
> 
> 对不起我迟到了。请尝试v9.1.1。
> 
> https://codesandbox.io/s/vmo9ypvwl7

expect support rotate

**Comment by kele5240** [comment] 2019-11-18 08:00
i can't use rotate when i use Rnd

**Comment by dengnan123** [comment] 2020-02-26 10:55
> @mfma @ryanlegler @koutsenko @g33kidd @gaddafirusli @travisdahl @kv9991 @cadrell0 @AhmedSayed77 @mecawish
> 
> Sorry for late. Please try v9.1.1.
> 
> https://codesandbox.io/s/vmo9ypvwl7

good!
