### ISSUE TITLE
Is it necessary to set the parent elements position?

### ISSUE THREAD

**Issue by Stianhn** [bokuweb/react-rnd#356] opened 2018-06-20 08:09 UTC
https://github.com/bokuweb/react-rnd/blob/9862fdfa63f2adb3f0b54aa88a544ee63af50d8c/src/index.js#L235

Why is this needed?

In general I would say it's bad practice to alter code that you do not control as it could have unwanted side effects and it can be hard to debug.

**Comment by hbogs** [comment] 2018-06-20 10:04
Oh man, I was just about to open a ticket for the same issue :)

This also causes a bug, where you cannot access a childs ref in componentDidMount ( and possibly componentDidUpdate, it depends). (Or you can, if you add a setTimeout as a workaround - but I dont like to add a "magic" timeout to fix issues like that).

See this example:
https://codesandbox.io/s/8229q39582

Since you need to edit the source code to add the proper fix (remove this line: https://github.com/bokuweb/react-rnd/blob/master/src/index.js#L427 ) its not easy to do on codesandbox, so I created a demo-repo here: https://github.com/hbogs/rnd-issue

**Comment by bokuweb** [comment] 2018-06-20 11:47
@Stianhn @hbogs Thanks for your report. I see...
It might be solved if you wrap `react-rnd` in `div`....???

``` JS
    return (
      <div style={{ position: 'relative' }}>
        <Draggable
          ref={(c: Draggable) => {
            this.draggable = c;
          }}
          ...
         />
      </div>
    );
```

**Comment by hbogs** [comment] 2018-06-20 12:18
@bokuweb 
Yeah, maybe that will work? Have to try it out I guess. 

In our use-case we only use `react-rnd` with a fixed position (by setting it in the style prop), so it wouldn't really affect us - other users who are relying on the parent changing to relative might have some issues though?

**Comment by hbogs** [comment] 2018-06-20 12:37
@bokuweb I think it deserves a `bug` label also, because of the issues with the `ref`'s, dont you agree?

**Comment by Stianhn** [comment] 2018-06-20 12:40
@bokuweb Thanks for the quick answer. We also set a fixed position that we pass trough props, so adding the div won't solve our issue.

But why is this function needed at all? I removed setParrentPoisition() and now it works as intended.

**Comment by bokuweb** [comment] 2018-06-20 12:50
@Stianhn Hmm, I see. Certainly there is a possibility of unnecessary. Investigate and delete it if we do not need it

**Comment by hbogs** [comment] 2018-06-20 12:54
@stianhn it still works for you because you (like us) set position:fixed on `react-rnd`, and because of that, the parents position will not have any effect (it could be whatever) - so in those cases, the modification of the parent position style is unnescessary.

I think by adding this wrapper, then the parent modification should be removed (thats how I understood it, but I might have misunderstood)

**Comment by bokuweb** [comment] 2018-06-20 13:00
@Stianhn 

> But why is this function needed at all? I removed setParrentPoisition() and now it works as intended.

Hmm,  If `setParrentPoisition()` removed,  `bound parent` story does not work correctly.
(You can see this story with `npm run storybook` and `open localhost:6016`.)

**Comment by bokuweb** [comment] 2018-06-20 13:02
If I change the code like below to avoid `setParrentPoisition()`, `bound multiple` story does not work....

```
 <div style={{ position: 'relative', width: '100%', height: '100%' }}>
        <Draggable
             ...
```

**Comment by hbogs** [comment] 2018-06-20 13:48
Maybe this should be connected with the bounds prop then? So f.ex something like this
```jsx
componentDidMount() {
  if (this.props.bounds === 'parent') {
    this.setParentPosition();
  }
}
```

I mean, setting the parent to relative only makes sense if you want to restrict the boundaries - and IMO that should be done explicitly. Currently you get this behavior automatically, even if you dont want it (f.ex if you want to use fixed positioning)

Also I did some testing and doesnt seem like the `if (!this.state.isMounted) return <div />;` does anything meaningful - do you remember why this was added? Removing this line, seems like everything works as expected, and also fixed the `ref` issue.

**Comment by bokuweb** [comment] 2018-06-20 13:59
@Stianhn I see. It looks good. Would you please create PR if you get a chance ?

**Comment by Stianhn** [comment] 2018-06-20 17:54
How about just documenting that any parent element you want to bound to needs to have ´position´set and rather throw a warning if the element doesn't have this set when you are trying to use bounding?

**Comment by hbogs** [comment] 2018-06-21 08:12
I like @Stianhn's proposal to show a warning better than my suggested solution - the only "downside" of that is that its a change in behavior, and probably warrants a major version bump.

Could be something like
```jsx
componentDidMount() {
  if (this.props.bounds === 'parent' && this.checkParentPosition !== 'relative') {
	console.warn('parent should have relative position set when using the "bounds" prop');
  }
}
```

WDYT @bokuweb ?

**Comment by bokuweb** [comment] 2018-06-21 08:19
@hbogs Thanks. It looks good. I'll apply this change for now, and so I 'll look for a better way.

**Comment by bokuweb** [comment] 2018-06-22 01:22
@Stianhn @hbogs I've just removed `isMounted` and `(!this.state.isMounted) return <div />;` for now. Because it seemed that there was no effect even if it was removed.

This version is published as `v7.4.2`. Would you please check this version, if you get a chance.

@hbogs 

> it could have unwanted side effects and it can be hard to debug.

I fully agree. But this change occurs critically break, and I would like to prevent users from setting `position` as much as possible... I would like to look for a better way to solve this issue.

I'd like to check this issue again. What problem occurred if you set `position: fixed` ?
If you ok, could you please provide reproduced project in codesandbox.

https://codesandbox.io/s/y3997qply9

**Comment by hbogs** [comment] 2018-06-22 08:27
@bokuweb Looks like this is breaking with 7.4.2 actually - did something else change also?

https://codesandbox.io/s/91wy1v5r9r

**Comment by bokuweb** [comment] 2018-06-22 08:42
😨 sorry... 7.4.2 unpublished.... i'll do investigation....

**Comment by bokuweb** [comment] 2018-06-22 09:41
@hbogs I've just published.v7.4.3.
I added `props.children` to dummy `div` for now.
Would you please check that `ref` issue solved if you get a chance.

And I'll consider to `fixed` issue.

@Stianhn  @hbogs  Would you please provide a project which is reproduced `fixed` issue.

**Comment by hbogs** [comment] 2018-06-22 10:57
In our project , we dont have any issues with setting `position: fixed` on rnd - it is just unnecessary to modify the parent's position in that case, since it will not make a difference. But I could see there could be cases where you would need the parent to stay `position: static`. In those cases, as a workaround, you could set `position: static !important` on the parent. Not a great workaround though, so should maybe look into another solution. I'll try to create some examples when I have some spare time.

Your fix for the `ref` issue is not really working either unfortunately... The good thing is that the app doesnt crash anymore, since the `ref` is no longer undefined. The problem comes when you want to do something with the ref, like setting focus f.ex. My initial example was a bit naive, sorry.. I added a more realistic example here, where you focus an inputfield: https://codesandbox.io/s/23o74kvwy0
The app doesnt crash anymore (which is good :) ), but the focus doesnt get set either, since the first time it renders it will set the focus to the inputfield - and then it will re-render since the isMounted flag is set, and a different inputfield is shown, but the code in the container component is not run again so the ref doesnt get updated.

So 7.4.3 is a slight improvement, but doesnt fix the issue unfortunately. I can dig into the issue a bit more myself as well when I have some spare time, and see if I can come up with a solution - maybe next week.

**Comment by Stianhn** [comment] 2018-06-22 11:10
@hbogs Setting position: static !important doesn't help as rnd replaces the style.

@bokuweb Why do you want to limit the users involvement i styling elements? If some code I'm importing to my project has requirements to the surroundings I would expect to find this explained in the documentation rather than the code changing this automagicly.

**Comment by hbogs** [comment] 2018-06-22 11:48
@Stianhn yes it will. !important wil override an inline style as well, unless the inline style also uses !important (which it doesnt in this case). Not a pretty workaround, but it will work.

**Comment by Stianhn** [comment] 2018-06-22 12:04
`      if (getComputedStyle(parent).position !== 'static') {
        return;
      }
      parent.style.position = 'relative';
`
Doesn't this just replace whatever is there?

**Comment by bokuweb** [comment] 2018-06-22 14:43
@Stianhn @hbogs I've just published v8.0.0-beta.0.
I removed `isMounted` state, dummy `<div />` and `setParentPosition()`.
Would you please check this version.

related https://github.com/bokuweb/react-rnd/pull/366

**Comment by hbogs** [comment] 2018-06-22 15:07
Im going away for the weekend, but Ill check on tuesday when Im back. Thanks.

**Closed** 2018-06-26 11:29 UTC
Labels: Discussion, bug, enhancement, help wanted

**Comment by Stianhn** [comment] 2018-06-26 11:30
This fixes my original concern so I'm closing this issue. Thank you @bokuweb
